#!/bin/sh
#
# start/stop nuage-amp-sync service
#
# chkconfig: 2345 99 5
# description: start/stop nuage-amp-sync processes
# processname: nuage-amp-sync
#
. /etc/rc.d/init.d/functions

proj="nuage-amp"
operation="sync"
prog=$proj-$operation
exec="/usr/bin/$proj $operation"
configs=(
    "/etc/$proj/$proj.conf" \
)
pidfolder="/var/run/$proj/"
pidfile="$pidfolder$prog.pid"

[ -e /etc/sysconfig/$prog ] && . /etc/sysconfig/$prog

lockfile=/var/lock/subsys/$prog

start() {
    #[ -x $prog ] || exit 5
    for config in ${configs[@]}; do
        [ -f $config ] || exit 6
    done
    echo -n $"Starting $prog: "
    [ -d "$pidfolder" ] || mkdir -p $pidfolder
    daemon --pidfile $pidfile "$exec --log-file /var/log/$proj/$operation.log ${configs[@]/#/--config-file } &>/dev/null & echo \$! > $pidfile"
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $lockfile
    return $retval
}


stop() {
    echo -n $"Stopping $prog: "
    killproc -p $pidfile $prog
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}


restart() {
    stop
    start
}

status() {
    if [ -f $pidfile ]; then
        PID=$(cat $pidfile)
        if [ -z "$(ps axf | grep ${PID} | grep -v grep)" ]; then
            echo "Service not running"
        else    
            echo "Service running, the PID is $PID"
        fi
    else
        echo "Service not running"
    fi
}


case "$1" in
start)
$1
;;
stop)
$1
;;
restart)
$1
;;
status)
$1
;;
*)
echo $"Usage: $0 {start|stop|restart|status}"
exit 1
esac

exit 0
